name: Actions Smoke Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test runner queue
    runs-on: ubuntu-latest

    steps:
      - name: Print diagnostic message
        run: echo "GitHub Actions runner queue works"
